query FieldValueByProjectV2ItemNodeIdAndFieldName($id: ID!, $name: String!) {
  node(id: $id) {
    ... on ProjectV2Item {
      fieldValueByName(name: $name) {
        # tipo pode ser tudo o que tá aqui ProjectV2ItemFieldValue
        ... on ProjectV2ItemFieldTextValue {
          text
        }
        ... on ProjectV2ItemFieldSingleSelectValue {
          name
        }
        ... on ProjectV2ItemFieldNumberValue {
          number
        }
        ... on ProjectV2ItemFieldIterationValue {
          title        
        }
        ... on ProjectV2ItemFieldDateValue {
          date
        }
      }
    }
	}
}
